train: [] # metrics that are calculated during training
inference: # metrics that are calculated during inference (eval)
  - _target_: src.metrics.ArgmaxCERMetric
    name: "CER_(Argmax)"
  - _target_: src.metrics.ArgmaxWERMetric
    name: "WER_(Argmax)"
  - _target_: src.metrics.BeamSearchCERMetric
    name: "CER_(BeamSearch-custom)"
    type: "custom"
    beam_size: 50
  - _target_: src.metrics.BeamSearchWERMetric
    name: "WER_(BeamSearch-custom)"
    type: "custom"
    beam_size: 50
