train:
  get_spectrogram: # special key for getting spectrogram
    _target_: torchvision.transforms.v2.Compose
    transforms:
      - _target_: torchaudio.transforms.MelSpectrogram
        sample_rate: 16000
      - _target_: src.transforms.RandomApply
        p: 0.8
        augmentation:
          - _target_: torchaudio.transforms.TimeMasking
            time_mask_param: 50
inference:
  get_spectrogram:
    _target_: torchaudio.transforms.MelSpectrogram
    sample_rate: 16000
